goolord/alpha-nvim

lua/alpha/themes/startify.lua
Export startify theme `mru()` for more flexible customization.
=> feat(startify): export mru() for more flexibility

lua/alpha.lua, lua/alpha/utils.lua
There is an `if_nil` function built in to neovim already, so don't need to redefine one.
(Defined [here](https://github.com/neovim/neovim/blob/47f99d66440ae8be26b34531989ac61edc1ad9fe/runtime/lua/vim/F.lua#L7))
=> refactor: replace `utils.from_nil` with `vim.F.if_nil`

lua/alpha.lua
Fixes an issue with highlight positioning with a `center` button with a `right` shortcut.
=> fix: hl for `center` button with `right` shortcut

lua/alpha/themes/dashboard.lua, lua/alpha/themes/startify.lua
Instead of automatically putting user into insert mode, i think it would be better not to. If i recall correctly, Startify behaves the same way.
=> removed automatically putting user into insert mode.

lua/alpha.lua
I have abstracted the loading condition for alpha-nvim into a separate function. There are basically two conditions:
1.  If the user have provided some file to nvim
2. The user does not provide a file, but uses some command line options.  In this case, for some of the command line options, it is still valid to show alpah-nvim startup sceen. For example, for option `-n` (no swap file), `-i` (use a certain shada file) etc.  Though the exact condition can be debated and I am open to suggestions and corrections.
I have also removed the `vim.o.modifiable` check since nvim does not support `-y` option and this is a nvim-only lua plugin, which does not support Vim.
On a side note, alpha-nvim used a non-conventional 4-space indentation, which makes it a little painful to work with since 2-space …
=> fix: wrong activation condition for alpha-nvim

lua/alpha.lua
This matters if `foldmethod=indent`. Without this change all indented 'alpha' text is shown in fold.
=> Open all folds inside 'alpha' buffer.

lua/alpha.lua
- Iterate `vim.v.argv` only once and see if there are any matches.
- Fixed some minor complaints that `luacheck` didn't like.
=> reduce number of lookups for should_skip

lua/alpha.lua
Ignore vim `-S` option that open session file.
I think it's better not start alpha-nvim when opening session with `nvim -S [session]`.
=> fix: do not start alpha-nvim when opening session

lua/alpha.lua
This allows formatting the full-file  with null-ls without issues
=> chore: fix stylua's inline hint

lua/alpha.lua, lua/alpha/themes/startify.lua
Convert globals to native lua modules which are both more performant and generally encouraged.
=> refactor: avoid using unnecessary globals

lua/alpha.lua
I don't want to start alpha-nvim with input from stdin.
`echo "aaaaa"	| nvim`
So, I'm porting this patch
https://github.com/glepnir/dashboard-nvim/blob/master/autoload/dashboard.vim#L36-L38
=> Skip input from stdin

lua/alpha/themes/startify.lua, lua/alpha/themes/theta.lua
On Windows, without this PR, path will be display as one for the whole path. Oppose to displaying a path and its file name separately on Unix-based systems.
=> Support Windows path for file button

lua/alpha.lua
When Alpha starts it sends the User AlphaReady autocommand. As a mirror
to that this patch adds a User AlphaClosed which runs when closing Alpha
to give users a chance to do whatever custom cleanup they need.
=> feat: send User AlphaClosed autocommand on close

lua/alpha.lua
Two small fixes
* The way `end_ln` was incremented before `alpha.highlight` meant that two calls to `vim.api.nvim_buf_add_highlight` were made for each text line (i.e. two highlight groups for each line rather than one), causing highlighting to affect the subsequent line.
* empty `opts` field in an element was preventing padding of line altogether
Before and after screenshots below w/ plain `startify` theme
<details>
<summary>Diff of modifications to `startify.lua`</summary>
```diff
diff --git a/lua/alpha/themes/startify.lua b/lua/alpha/themes/startify.lua
index c38982e..8a6be2d 100644
--- a/lua/alpha/themes/startify.lua
+++ b/lua/alpha/themes/startify.lua
@@ -177,7 +177,9 @@ local section = {
val = {
{ type = "padding", val = 1 },
{ type = "text", val = "MRU", opts = { hl = …
```
=> Fix text highlighting spilling over to next line

lua/alpha/fortune.lua
I wanted to provide the possibility to configure an own fortune list. To prevent backwards compatibility, main now checks if a table or a number is provided.
=> Make fortune_list an option

doc/alpha.txt, lua/alpha.lua, lua/alpha/term.lua, lua/alpha/themes/dashboard.lua
Firstly, I want to say this is heavily inspired by the awesome work on #63 by Ben. This pull request builds on that. Secondly, under no pressure to merge this into main at all. This is simply my itch that I wanted to scratch :wink:.
The primary aim of this pull request is to create a simple API (fitting in with the existing API) which displays the output from a command as my header in my existing dashboard.
I tried out [dashboard.nvim](https://github.com/glepnir/dashboard-nvim) again recently and the only positive it has over this plugin is its ability to display the output of a given command. It turned out it mattered to me quite a lot as I chase a glorious aesthetic of a Neovim dashboard.
I analysted #63 quite significantly alongside the dashboard.nvim implementation and in truth, …
=> feat: command output as a header

lua/alpha/themes/startify.lua, lua/alpha/themes/theta.lua
Fixing #52 
It is `off` by default, as to not cause any breaking changes.
If you want to use this just do : 
```lua
local theme = require("alpha.themes.theta") --or require("alpha.themes.startify")
theme.mru_opts.autocd = true
alpha.setup(theme.config)
```
=> Auto cd when selecting file from MRU

lua/alpha/themes/theta.lua
Exporting the MRU function will allow users to customize their theta config with respect to MRU specifics, e.g. the shortcut starting number or the total number of items to be displayed.
Also see discussion https://github.com/goolord/alpha-nvim/discussions/159.
=> Export MRU function in theta theme

README.md, doc/alpha.txt
The `nvim-web-devicons` repo was transferred from `kyazdani42/nvim-web-devicons` to [`nvim-tree/nvim-web-devicons`](https://github.com/nvim-tree/nvim-web-devicons).
This updates the docs to point to the updated repo.
=> Update nvim-web-devicons references

lua/alpha.lua
Proposed fix for the `alpha.start` command. This exposes the configuration from the `setup` call as `require("alpha").config`. This way you can call it with something like
```lua
require("alpha").start(true, require("alpha").config)
require("alpha").start(false, require("alpha").config)
```
Resolves #175
=> fix: store alpha configuration to a user accessible variable

lua/alpha/term.lua
Similarly to how `val` can be a function, this lets users define a function that returns the terminal command.
Why? Users might want to do expensive FS tasks in order to, say, get a random script and determine its dimensions.
Rather than running these expensive tasks in each start up in the `config` function, it's better to defer these until alpha actually draws the output
=> feat: allow terminal cmd to be a function

doc/alpha.txt, lua/alpha.lua
This plugin binds `<CR>` and `<M-CR>` by default, which can conflict with custom keymaps. This MR adds an option to change these default mappings by passing new argument in `setup()`.
Previous binds are now default values for these options. Values can be either a string or a list of strings (one or many mappings), or `nil` (remove mapping).
Here is an example configuration:
```lua
require('alpha').setup {
...,
opts = {
keymap = {
-- Press action is now triggered for both "ENTER" and "l"
press = { '<CR>', 'l' },
-- Queue press is removed
queue_press = nil
}
}
}
```
=> feat: add an option to pass keymaps

lua/alpha/term.lua
This change adds logic that allows the terminal window to reposition accordingly when a window split occurs. For example, when neotree is made visible while alpha is also visible.
=> Reposition the term as needed

lua/alpha.lua
Fixes #238 
This solution is inspired from [`mini.starter`](https://github.com/echasnovski/mini.nvim/blob/a1b96721dea1e9c7aeeb4bd402b9debebf38ed23/lua/mini/starter.lua#L1408-L1431). Note how the comment there explains how @echasnovski had encountered a similar (?) issue using `line2byte` in the past.
=> fix: replace line2byte check

lua/alpha/term.lua
Hope you're all having a good day.
Encountered a problem when restoring sessions in AstroVim.
To see the problem:
1. Install [AstroVim](https://github.com/AstroNvim/AstroNvim/tree/main)
2. Add the following to `~/.config/nvim/lua/user/plugins/user.lua`:
```lua
{
"goolord/alpha-nvim",
opts = function()
local dashboard = require "alpha.themes.dashboard"
require('alpha.term')
dashboard.section.terminal.command = "cowsay I have herd you have a bug. Moo-tivating fix in progress."
dashboard.section.terminal.width = 42
dashboard.section.terminal.height = 16
dashboard.section.terminal.opts.redraw = true
dashboard.section.terminal.opts.window_config.zindex = 1
dashboard.section.header.val = {
"NeoVim",
}
dashboard.section.terminal.opts.hl = "DashboardHeader"
dashboard.section.footer.opts.hl = …
```
=> fix: only delete valid buffers on alpha close

lua/alpha.lua
This directly addresses two things:
1. Fixed handling of multi-mode mappings
2. Allow passing a lua function as the mapping RHS
`opts.keymap` is now passed to `vim.keymap.set` instead of `nvim_buf_set_keymap` because it handles all of the work needed to support multi-mode mappings and functions as RHS, eliminating most of the work needed to be done here.
I have a button that loads the last saved session via persistence.nvim and prints a message. With this patch, I can define a button like this:
```lua
local function callback()
print('Loading session')
require('persistence').load { last = true }
end
local button = {
type = 'button',
val = 'Restore Last Session',
on_press = callback,
opts = {
-- blah blah
keymap = { 'n', shortcut, callback, {} }
}
}
```
=> fix: Button keymap assignment

lua/alpha.lua
Problem:
- Alpha use a autocmd base on `BufUnload` to close alpha's instance.
- `BufUnload` will not be triggered by source a session file.
- Alpha will still try to redraw after buffer closed by loading a session, causing invalid buffer error since these autocmds were not cleared properly.
Solution:
- Add autocmd base on `SessionLoadPost` to close alpha after sourcing a session file.
=> Fix: Close alpha after SessionLoadPost.

lua/alpha/themes/theta.lua
Hi,
The config path is hardcoded in the theta theme yielding an error on Windows when pressing `c`.
I'm aware of PR #280 but i think using the builtin vim function `stdpath('config')` is simpler and easier to understand for new users to customize the theta theme.
=> Fix Theta theme config path

README.md, doc/alpha.txt, lua/alpha/themes/startify.lua, lua/alpha/themes/theta.lua, lua/alpha/utils.lua
https://github.com/echasnovski/mini.icons
- mini.icons has both "glyph" and "ascii" style.
- faster then nvim-web-devicons.
- default use mini.icons, config provider in require("alpha.themes.startify").file_icons.provider
- backward compatibility, require("alpha.themes.startify").nvim_web_devicons mark `deprecated`
- fix get_extension when path has '.', ex: a/b.c/makefile
- use vim.notify warning instead of stacktrace error
=> feat: support mini.icons

README.md
A code snippet in the README was missing syntax colors, it looked a bit odd.
=> fix: readme code snippet missing syntax colors

lua/alpha.lua
Hi @goolord thanks for this great plugin,
This PR fixes a deprecation warning from Neovim related to `vim.validate`.
- Replaces old `vim.validate({...})` call with the new 4-argument signature.
- Ensures compatibility with upcoming Neovim 0.12 and 1.0 versions.
```
==============================================================================
vim.deprecated:                       require("vim.deprecated.health").check()
~
- ⚠️ WARNING vim.validate is deprecated. Feature will be removed in Nvim 1.0
- ADVICE:
- stack traceback:
/Users/dimasprabowo/.local/share/nvim/site/pack/packer/start/alpha-nvim/lua/alpha.lua:730
/Users/dimasprabowo/.config/nvim/lua/98prabowo/plugins/dashboard.lua:78
[C]:-1
/Users/dimasprabowo/.config/nvim/init.lua:13
```
Fixes #318
=> fix: update vim.validate calls to the new syntax
